// scripts/_seed/persona-v1-hash.ts
//
// Computes the canonical serialization + sha256 of PROCUREMENT_PERSONA v1,
// using the EXACT canonicalSerializePersona function from lib/prompt/compile.ts.
// Output is pasted into scripts/016_persona_and_analysis_runs.sql.
//
// Run with:  npx tsx scripts/_seed/persona-v1-hash.ts

import crypto from 'node:crypto';
import { PROCUREMENT_PERSONA } from '../../lib/prompt/persona-procurement';
import { canonicalSerializePersona } from '../../lib/prompt/compile';

const canonical = canonicalSerializePersona(PROCUREMENT_PERSONA);
const hash = crypto.createHash('sha256').update(canonical, 'utf8').digest('hex');

console.log('---- canonical JSON (length=' + canonical.length + ') ----');
console.log(canonical);
console.log('---- sha256 hex ----');
console.log(hash);
console.log('---- ready-to-paste SQL block ----');
console.log(`-- AUTOGENERATED by scripts/_seed/persona-v1-hash.ts -- DO NOT HAND-EDIT
INSERT INTO persona_versions (
  persona_id, version_number, status, content, content_hash, notes,
  created_by, published_at, published_by
) VALUES (
  'procurement', 1, 'published',
  $jsonb$${canonical}$jsonb$::jsonb,
  '${hash}',
  'Initial migration from lib/prompt/persona-procurement.ts',
  '8a652f73-1f2d-407b-bf18-32a3ddd1b979', now(), '8a652f73-1f2d-407b-bf18-32a3ddd1b979'
);`);
