-- 008_refund_reviews_queue.sql
-- Adds a service-role-only queue for refund/dispute manual review.

CREATE TABLE IF NOT EXISTS public.refund_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id TEXT NOT NULL UNIQUE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  stripe_charge_id TEXT,
  amount_refunded BIGINT NOT NULL DEFAULT 0,
  reason TEXT,
  review_type TEXT NOT NULL CHECK (review_type IN ('refund', 'dispute')),
  reviewed_at TIMESTAMPTZ,
  decision TEXT CHECK (decision IN ('approve_keep_access', 'downgrade_now', 'investigate')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS refund_reviews_user_id_idx ON public.refund_reviews(user_id);
CREATE INDEX IF NOT EXISTS refund_reviews_review_type_idx ON public.refund_reviews(review_type);
CREATE INDEX IF NOT EXISTS refund_reviews_created_at_idx ON public.refund_reviews(created_at DESC);
CREATE INDEX IF NOT EXISTS refund_reviews_unreviewed_idx
  ON public.refund_reviews(created_at DESC)
  WHERE reviewed_at IS NULL;

ALTER TABLE public.refund_reviews ENABLE ROW LEVEL SECURITY;
-- No policies = service-role-only access.
