-- scripts/016_persona_and_analysis_runs.sql
--
-- Tier 1 modular analysis cutover — Phase 2 DB migration.
--
-- Creates:
--   * public.users.is_platform_admin (boolean)
--   * personas / persona_versions (with circular FK ordering + partial unique
--     draft index + JSONB content shape CHECK + RLS)
--   * Seed v1 procurement persona (content + content_hash generated by
--     scripts/_seed/persona-v1-hash.ts from lib/prompt/persona-procurement.ts)
--   * analysis_runs (with persona_version_id NOT NULL FK inline, partial unique
--     one-current-per-contract index, SELECT-only RLS, explicit REVOKE)
--   * contracts.current_run_id (uuid read pointer)
--
-- Drops:
--   * public.contract_analyses (in a SEPARATE transaction so earlier DDL
--     persists if drop fails; pre-drop dependency assertion; NOT CASCADE)
--
-- Bootstrap admin: 8a652f73-1f2d-407b-bf18-32a3ddd1b979 (alex.bubier@gmail.com).
-- Refs: spec § Part 1 Data Model + § Part 5 Migration story + plan P2.1–P2.4.

\set ON_ERROR_STOP on

-- ============================================================================
-- Transaction 1 — schema + seed
-- ============================================================================
BEGIN;

-- ---------------------------------------------------------------------------
-- (0) Admin flag on public.users + bootstrap admin row.
-- ---------------------------------------------------------------------------
ALTER TABLE public.users
  ADD COLUMN is_platform_admin boolean NOT NULL DEFAULT false;

UPDATE public.users
   SET is_platform_admin = true
 WHERE id = '8a652f73-1f2d-407b-bf18-32a3ddd1b979';

-- Sanity: bootstrap admin row must exist + be flagged. If not, the row is
-- missing from public.users — fail loudly before persona/run tables reference it.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.users
     WHERE id = '8a652f73-1f2d-407b-bf18-32a3ddd1b979'
       AND is_platform_admin = true
  ) THEN
    RAISE EXCEPTION 'Bootstrap admin row missing from public.users — populate before running 016';
  END IF;
END$$;

-- ---------------------------------------------------------------------------
-- (a) personas — created WITHOUT current_version_id FK (added in step d).
-- ---------------------------------------------------------------------------
CREATE TABLE personas (
  id                  text PRIMARY KEY,
  current_version_id  uuid,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- (b) persona_versions with FK back to personas.
-- ---------------------------------------------------------------------------
CREATE TABLE persona_versions (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  persona_id      text NOT NULL REFERENCES personas(id),
  version_number  int  NOT NULL,
  status          text NOT NULL DEFAULT 'published',
  content         jsonb NOT NULL,
  content_hash    text NOT NULL,
  notes           text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  created_by      uuid NOT NULL REFERENCES public.users(id),
  published_at    timestamptz,
  published_by    uuid REFERENCES public.users(id),
  UNIQUE (persona_id, version_number)
);

-- ---------------------------------------------------------------------------
-- (c) Partial unique index: at most one draft per persona.
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX persona_versions_one_draft_per_persona
  ON persona_versions (persona_id)
  WHERE status = 'draft';

-- ---------------------------------------------------------------------------
-- (d) Cross-FK: personas.current_version_id → persona_versions(id).
-- ---------------------------------------------------------------------------
ALTER TABLE personas
  ADD CONSTRAINT personas_current_version_fk
  FOREIGN KEY (current_version_id) REFERENCES persona_versions(id);

-- CHECK constraint on JSONB shape — minimal guard against malformed content.
ALTER TABLE persona_versions
  ADD CONSTRAINT persona_versions_content_shape
  CHECK (
    jsonb_typeof(content -> 'description') = 'string'
    AND jsonb_typeof(content -> 'keyClauses') = 'array'
    AND jsonb_typeof(content -> 'riskAreas') = 'array'
  );

-- ---------------------------------------------------------------------------
-- (e) Seed v1 persona row. content + content_hash come from
--     scripts/_seed/persona-v1-hash.ts (sha256 = b68d55f5...).
-- ---------------------------------------------------------------------------
INSERT INTO personas (id) VALUES ('procurement');

-- AUTOGENERATED by scripts/_seed/persona-v1-hash.ts -- DO NOT HAND-EDIT
INSERT INTO persona_versions (
  persona_id, version_number, status, content, content_hash, notes,
  created_by, published_at, published_by
) VALUES (
  'procurement', 1, 'published',
  $jsonb${"id":"procurement","description":"You are a buyer-side procurement counsel. Analyze contracts from the buyer's perspective.\nSurface terms that disadvantage the buyer and lead the summary with the strongest\nnegotiation leverage points.\n\nCITATION REQUIREMENTS (strict, enforced by schema and post-validation):\n\n- Every risk you report MUST include either:\n  (a) evidence.type = \"quoted\" with clause_reference and a verbatim quoted_text\n      pulled directly from the contract — at least 20 characters, copied exactly\n      (not paraphrased, not summarized); OR\n  (b) evidence.type = \"absence\" with a missing_concept describing what is not\n      present (only when the risk is about a missing protection, not a stated term).\n\n- Every key clause you report MUST be either:\n  (a) presence.status = \"present\" with quoted_text copied verbatim from the\n      contract — at least 20 characters; OR\n  (b) presence.status = \"absent\" with no quoted_text — clause is not in the contract.\n\n- Do NOT paraphrase, infer, or fabricate quotes. The system verifies every\n  quoted_text appears in the contract. If your quote is not verifiable, the\n  entire analysis is rejected. When in doubt, mark as absent or absence-based.\n\nrisk_score scale (anchored — use these bands, do not invent new ones):\n  0–20   Boilerplate-safe. Standard mutual terms, no material buyer disadvantage.\n  21–50  Minor concerns. Imperfect but acceptable with awareness.\n  51–80  Material buyer risks. Should be negotiated before signature.\n  81–100 Deal-breakers. Requires legal escalation or walk-away.","keyClauses":[{"id":"termination","label":"Termination","hint":"For convenience, for cause, notice periods, wind-down."},{"id":"auto_renewal","label":"Auto-Renewal","hint":"Opt-out windows, notice mechanics, price escalation on renewal."},{"id":"liability_cap","label":"Limitation of Liability","hint":null},{"id":"indemnification","label":"Indemnification","hint":"Mutuality, carve-outs, defense vs. indemnify, IP indemnity."},{"id":"data_and_ip","label":"Data & IP Rights","hint":"Ownership of buyer data, derived works, model-training rights."},{"id":"payment_terms","label":"Payment Terms","hint":"Front-loaded commitments, true-up mechanics, late fees."},{"id":"sla","label":"Service Levels","hint":null},{"id":"confidentiality","label":"Confidentiality","hint":null},{"id":"governing_law","label":"Governing Law & Venue","hint":null}],"riskAreas":[{"id":"unfavorable_termination","label":"Unfavorable Termination Terms","hint":null},{"id":"auto_renewal_trap","label":"Auto-Renewal Trap","hint":"Short opt-out windows, hard-to-discover renewal."},{"id":"vendor_favorable_liability","label":"Vendor-Favorable Liability Cap","hint":null},{"id":"indemnification_gap","label":"Indemnification Gap","hint":"Asymmetric protection, narrow IP indemnity."},{"id":"data_ownership_erosion","label":"Buyer Data/IP Ownership Erosion","hint":null},{"id":"frontloaded_payment","label":"Front-Loaded Buyer Commitment","hint":null},{"id":"weak_sla","label":"Weak or Unenforceable SLA","hint":null},{"id":"jurisdiction_risk","label":"Unfavorable Jurisdiction or Venue","hint":null}]}$jsonb$::jsonb,
  'b68d55f51d2fff927fed2cf24db995bdc4868b9d647f3bfa365762064725cf03',
  'Initial migration from lib/prompt/persona-procurement.ts',
  '8a652f73-1f2d-407b-bf18-32a3ddd1b979', now(), '8a652f73-1f2d-407b-bf18-32a3ddd1b979'
);

-- Wire current_version_id on the persona row.
UPDATE personas
   SET current_version_id = (
     SELECT id FROM persona_versions
      WHERE persona_id = 'procurement' AND version_number = 1
   )
 WHERE id = 'procurement';

-- ---------------------------------------------------------------------------
-- (f) Tighten invariant after seed — every persona row MUST point to a version.
-- ---------------------------------------------------------------------------
ALTER TABLE personas
  ALTER COLUMN current_version_id SET NOT NULL;

-- ---------------------------------------------------------------------------
-- (g) analysis_runs with persona_version_id NOT NULL FK inline + all telemetry.
-- ---------------------------------------------------------------------------
CREATE TABLE analysis_runs (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  contract_id        uuid NOT NULL REFERENCES contracts(id),
  status             text NOT NULL,
  is_current         boolean NOT NULL DEFAULT false,
  output             jsonb,
  diagnostics        jsonb NOT NULL DEFAULT '[]',
  user_context       text,
  persona_id         text NOT NULL,
  persona_version_id uuid NOT NULL REFERENCES persona_versions(id),
  persona_hash       text NOT NULL,
  core_version       text NOT NULL,
  model_id           text NOT NULL,
  model_params       jsonb NOT NULL,
  prompt_hash        text NOT NULL,
  context_hash       text,
  input_tokens       int,
  output_tokens      int,
  cost_usd_micros    bigint,
  latency_ms         int,
  created_at         timestamptz NOT NULL DEFAULT now(),
  completed_at       timestamptz
);

-- Hard invariant: ≤ 1 current run per contract. Used by promoteToCurrent atomicity.
CREATE UNIQUE INDEX analysis_runs_one_current_per_contract
  ON analysis_runs (contract_id) WHERE is_current;

-- ---------------------------------------------------------------------------
-- (h) contracts.current_run_id — read pointer for the UI's "latest" query.
-- ---------------------------------------------------------------------------
ALTER TABLE contracts ADD COLUMN current_run_id uuid REFERENCES analysis_runs(id);

-- ---------------------------------------------------------------------------
-- RLS: analysis_runs SELECT-only for users (service role bypasses).
-- ---------------------------------------------------------------------------
ALTER TABLE analysis_runs ENABLE ROW LEVEL SECURITY;

CREATE POLICY analysis_runs_select ON analysis_runs
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM contracts c WHERE c.id = analysis_runs.contract_id
    )
  );

-- Explicit revoke (belt-and-suspenders above RLS — anon/authenticated cannot
-- write even if a future policy is accidentally permissive).
REVOKE INSERT, UPDATE, DELETE ON analysis_runs FROM authenticated, anon;

-- ---------------------------------------------------------------------------
-- RLS: personas / persona_versions admin-only writes (is_platform_admin = true).
-- ---------------------------------------------------------------------------
ALTER TABLE personas ENABLE ROW LEVEL SECURITY;
ALTER TABLE persona_versions ENABLE ROW LEVEL SECURITY;

CREATE POLICY personas_admin_all ON personas
  USING (EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.is_platform_admin = true))
  WITH CHECK (EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.is_platform_admin = true));

CREATE POLICY persona_versions_admin_all ON persona_versions
  USING (EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.is_platform_admin = true))
  WITH CHECK (EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.is_platform_admin = true));

-- Plus user-visible SELECT for persona content of runs they can see.
CREATE POLICY persona_versions_select_via_run ON persona_versions
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM analysis_runs ar
       WHERE ar.persona_version_id = persona_versions.id
    )
  );

COMMIT;

-- ============================================================================
-- Transaction 2 — drop legacy contract_analyses
--
-- Separated so earlier DDL persists even if the drop fails. The pre-drop
-- assertion catches any view/FK/function/trigger still referencing the table.
-- ============================================================================
BEGIN;

DO $$
DECLARE
  dep_count int;
BEGIN
  SELECT count(*) INTO dep_count FROM (
    SELECT 1 FROM information_schema.views
     WHERE view_definition ILIKE '%contract_analyses%'
    UNION ALL
    SELECT 1 FROM pg_constraint
     WHERE contype = 'f'
       AND (conrelid::regclass::text = 'contract_analyses'
            OR confrelid::regclass::text = 'contract_analyses')
    UNION ALL
    SELECT 1 FROM pg_proc WHERE prosrc ILIKE '%contract_analyses%'
    UNION ALL
    SELECT 1 FROM pg_trigger
     WHERE tgrelid::regclass::text = 'contract_analyses'
       AND NOT tgisinternal
  ) deps;

  IF dep_count > 0 THEN
    RAISE EXCEPTION 'contract_analyses still has % dependencies — run scripts/_checks/contract_analyses_deps.sql for details', dep_count;
  END IF;
END$$;

-- intentionally NOT CASCADE — if any dependency slipped past the assertion,
-- the drop fails safely instead of silently destroying a dependent object.
DROP TABLE IF EXISTS contract_analyses;

COMMIT;
